name = "mohamedbannnona/dissatisfiedprosignal"
version = "0.1.0"
description = "fast signal implementation"
authors = ["Mohamed Bannona"]
repository = "https://github.com/MohamedBannona/DissatisfiedProSignal"
license = "CC0-1.0"

includes = [
	"pesde.toml",
    "src",
    "src/**",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
argon_sync_config_generator = ".pesde/scripts/argon_sync_config_generator.luau"
argon_sourcemap_generator = ".pesde/scripts/argon_sourcemap_generator.luau"

rojo_sync_config_generator = ".pesde/scripts/rojo_sync_config_generator.luau"
rojo_sourcemap_generator = ".pesde/scripts/rojo_sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
argon = { name = "pesde/argon", version = "^2.0.23", target = "lune" }
